const MainList = [
  {
    word: "erneut",
    text_fa: "دوباره",
    // text_en:"anew",
    // voice_en:"دوباره",
    voice_en: "",
    picture: "erneut.jpg",
  },
  {
    word: "hochladen",
    text_fa: "آپلود",
    // text_en:"anew",
    // voice_en:"دوباره",
    voice_en: "hochladen.mp3",
    picture: "hochladen.png",
  },
  {
    word: "herunterladen",
    text_fa: "دانلود",
    // text_en:"anew",
    // voice_en:"دوباره",
    voice_en: "herunterladen.mp3",
    picture: "herunterladen.png",
  },
  {
    word: "Dorf",
    text_fa: "روستا",
    // text_en:"anew",
    // voice_en:"دوباره",
    voice_en: "Dorf.mp3",
    picture: "dorf.jpg",
  },
  {
    word: "Freunde",
    text_fa: "دوستان",
    // text_en:"anew",
    // voice_en:"دوباره",
    voice_en: "Freunde.mp3",
    picture: "freunde.jpg",
  },
  {
    word: "miteinander",
    text_fa: "به اشتراک",
    // text_en:"anew",
    // voice_en:"دوباره",
    voice_en: "miteinander.mp3",
    picture: "miteinander.jpg",
  },
  {
    word: "besprechen",
    text_fa: "بحث و گفتگو",
    // text_en:"anew",
    // voice_en:"دوباره",
    voice_en: "miteinander.mp3",
    picture: "besprechen.jpg",
  },
];

export const myStore = new Proxy(MainList, {});
